import type { Metadata } from 'next';
import { Indie_Flower, Inter, Parisienne } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const parisienne = Parisienne({ weight: '400', subsets: ['latin'] });
export const indieFlower = Indie_Flower({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primary ${parisienne.className}`}>{children}</body>
    </html>
  );
}
